
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - lambda-mongo-db
    env_file:
      - "frontend/.env"
    volumes:
      - ./frontend:/usr/local/app/frontend
      - /usr/local/app/frontend/node_modules
    profiles:
      - dev

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 3000:3000
    networks:
      - lambda-mongo-db
    env_file:
      - "frontend/.env"
    profiles:
      - prod

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 4000:4000
    networks:
      - lambda-mongo-db
    depends_on:
      - mongo
    env_file:
      - "backend/.env"
    environment:
      - DB_URI=mongodb://mongo:27017/lambda
    volumes:
      - ./backend:/usr/local/app/backend
      - /usr/local/app/backend/node_modules
    profiles:
      - dev

  backend-prod:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 4000:4000
    networks:
      - lambda-mongo-db
    depends_on:
      - mongo
    env_file:
      - "backend/.env"
    environment:
      - DB_URI=mongodb://mongo:27017/lambda
    profiles:
      - prod

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - lambda-mongo-db
    volumes:
      - /home/ubuntu/mongo-data:/data/db # Ensure this volume is created externally and at the correct path
  
networks:
  default:
    name: lambda-mongo-db