name: Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Pull main and deploy the latest code
    runs-on: [self-hosted, eee-ims]
    steps:
      - name: clone repo and update
        run: |
          cd /home/ubuntu/lambda-finance
          git pull
          docker compose --profile prod up --build -d